
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhzpopoqdvrtxlxivsfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoenBvcG9xZHZydHhseGl2c2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTEzMjgsImV4cCI6MjA2MTMyNzMyOH0.ysNwTi7pkBDLKxzQR9rXDcGjjtWlKktpZDDyRMtvrxA";

// Create a function that configures the Supabase client with a Clerk session token
export const createClerkSupabaseClient = (getToken: () => Promise<string | null>) => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      headers: {
        // Set the Clerk session token in the authorization header
        async Authorization() {
          const token = await getToken();
          if (token) {
            return `Bearer ${token}`;
          }
          return '';
        }
      },
    },
  });
};

// Default supabase client for unauthenticated requests
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
