// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhzpopoqdvrtxlxivsfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoenBvcG9xZHZydHhseGl2c2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTEzMjgsImV4cCI6MjA2MTMyNzMyOH0.ysNwTi7pkBDLKxzQR9rXDcGjjtWlKktpZDDyRMtvrxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);